version: "3.2"
services:
  flights-rmq:
    image: 524881529748.dkr.ecr.ap-south-1.amazonaws.com/flights-rmq:qa-integration
    container_name: 'flights-rmq'
    healthcheck:
      test: ["CMD", "wget", "-S", "http://localhost:15672/#/"]
      interval: 30s
      timeout: 10s
      retries: 8
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_PASS=flights"
      - "RABBITMQ_DEFAULT_USER=flights"
      - "RABBITMQ_DEFAULT_VHOST=/flights"
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge