package com.mmt.flights.common.logging.metric;

public enum MetricServices {

	PNR_RETRIEVE_REQUEST_TOTAL,
	PNR_RETRIEVE_REQUEST_SUCCESS,
	PNR_RETRIEVE_LATENCY,
	PNR_RETRIEVE_REQUEST_ERROR,
	PNR_RETRIEVE_TIME_OUT,
	PNR_RETRIEVE_NETWORK_CALL_LATENCY,

	PNR_CANCEL_REQUEST_COUNTER,
	VOID_PNR_CANCEL_REQUEST_COUNTER,
	PNR_CANCEL_REQUEST_SUCCESS,
	PNR_CANCEL_LATENCY,
	PNR_CANCEL_REQUEST_ERROR,
	PNR_CANCEL_TIME_OUT,
	PNR_CANCEL_RELEASE_TIME_OUT,
	PNR_CANCEL_NETWORK_CALL_LATENCY,
	PNR_CANCEL_RELEASE_NETWORK_CALL_LATENCY,

	CHECK_REFUND_REQUEST_COUNTER,
	CHECK_REFUND_NETWORK_CALL_LATENCY,

	VALIDATE_CANCEL_REQUEST_ERROR,
	VALIDATE_CANCEL_TIME_OUT,
	VALIDATE_CANCEL_PNR_RETRIEVE_LATENCY,
	VALIDATE_CANCEL_REQUEST_SUCCESS,
	VOID_NETWORK_CALL_LATENCY,
	

	ODC_PENALTY_NOT_FOUND,
    PNR_CANCEL_RELEASE_REQUEST_TOTAL, PNR_CANCEL_RELEASE_REQUEST_ERROR, PNR_CANCEL_RELEASE_REQUEST_LATENCY, PNR_CANCEL_RELEASE_REQUEST_SUCCESS;


}
